services:
  - type: web
    name: hranitel-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip uninstall -y python-telegram-bot
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false