services:
  - type: web
    name: hranitel-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        fromDatabase: false
      - key: OPENAI_API_KEY
        fromDatabase: false